name: Node CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.GH_TOKEN }}
    - uses: actions/setup-node@v4
      with:
        node-version: 18
    - name: Install and test
      run: |
        yarn
        yarn test
      env:
        CI: true
    - name: Run binary with no args
      run: node ./bin/clj-kondo
      env:
        CI: true
